import {SomniaMarkets, SOMNIA_MAINNET_ADDRESSES, SOMNIA_TESTNET_ADDRESSES, isBinaryMarket} from '@somnia-chain/markets-sdk';
import {somniaMainnet, somniaShannon} from '@somnia-chain/markets-sdk/chains';
import type {Market,OrderBook,Trade,Side,CalibrationMetrics,CalibrationBin} from '@eventlens/shared';
import type {DreamDexAdapter} from './index.js';
import {fairProbability,clamp} from '@eventlens/quant';

export interface SomniaConfig { indexerUrl:string; wsRpcUrl:string; privateKey?:`0x${string}`; network:'mainnet'|'shannon'; }
const asNumber=(v:any)=>typeof v==='bigint'?Number(v):Number(v??0);
const millis=(v:any)=>{const n=asNumber(v); return n>1e12?n:n*1000;};
const assetOf=(i:any,x:any)=>(String(i.asset??i.symbol??x.base??'BTC').toUpperCase().startsWith('ETH')?'ETH':'BTC') as 'BTC'|'ETH';
const volatilityFor=(asset:'BTC'|'ETH')=>asset==='BTC'?0.72:0.95;

export class SomniaDreamDexAdapter implements DreamDexAdapter {
  private exchange:any; private network:'mainnet'|'shannon'; private privateKey?:`0x${string}`; private calibrationCache?:{at:number;value:CalibrationMetrics};
  constructor(config:SomniaConfig){this.network=config.network;this.privateKey=config.privateKey;const isMainnet=config.network==='mainnet';this.exchange=new SomniaMarkets({indexerUrl:config.indexerUrl,wsRpcUrl:config.wsRpcUrl,chain:isMainnet?somniaMainnet:somniaShannon,addresses:isMainnet?SOMNIA_MAINNET_ADDRESSES:SOMNIA_TESTNET_ADDRESSES,...(config.privateKey?{privateKey:config.privateKey}:{})});}
  async discoverMarkets():Promise<Market[]>{const rows=Object.values(await this.exchange.loadMarkets(true)) as any[]; return rows.filter((x:any)=>x.active&&isBinaryMarket(x.info)).map((x:any)=>{const i=x.info;const up=x.outcomes?.[0];const down=x.outcomes?.[1];const upPrice=Number(up?.price??i.lastPrice??0);return {id:String(i.marketId),marketId:String(i.marketId),symbol:String(up?.symbol??x.symbol??i.marketId),asset:assetOf(i,x),intervalSeconds:Number(i.intervalSeconds??i.intervalSec??900),openPrice:Number(i.openPrice??0),currentPrice:Number(i.currentPrice??i.markPrice??0),expiry:millis(i.expiryTimestampMs??i.expiry),status:'TRADING',upPrice,downPrice:Number(down?.price??(1-upPrice)),liquidity:Number(i.liquidity??i.cumulativeQuoteVolume??0),spread:0} as Market;});}
  private async find(marketId:string){const markets=await this.exchange.loadMarkets(true);return Object.values(markets).find((x:any)=>String(x.info?.marketId)===marketId) as any;}
  async orderBook(marketId:string):Promise<OrderBook>{const m=await this.find(marketId);if(!m?.outcomes?.[0]?.symbol)return {bids:[],asks:[]};const b=await this.exchange.fetchOrderBook(m.outcomes[0].symbol,10);return {bids:(b.bids??[]).map((x:any)=>({price:Number(x[0]),quantity:Number(x[1])})),asks:(b.asks??[]).map((x:any)=>({price:Number(x[0]),quantity:Number(x[1])}))};}
  async execute(input:{marketId:string;side:Side;quantity:number;maxPrice:number;wallet:string}):Promise<Trade>{if(!this.privateKey) throw new Error('LIVE execution requires SOMNIA_PRIVATE_KEY on the API server');const m=await this.find(input.marketId);if(!m)throw new Error('Market not found');const onchain=await this.exchange.client.getMarketOnchain(input.marketId as `0x${string}`);if(onchain.status!==1)throw new Error(`Market is not Trading (status ${onchain.status})`);const symbol=input.side==='UP'?m.outcomes[0].symbol:m.outcomes[1].symbol;const result=await this.exchange.createOrder(symbol,'limit','buy',input.quantity,input.maxPrice,{timeInForce:'IOC'});const receipt=(result.info as any)?.receipt;return {id:String(result.id??Date.now()),marketId:input.marketId,wallet:input.wallet,side:input.side,quantity:input.quantity,entryPrice:input.maxPrice,executionPrice:input.maxPrice,cost:input.maxPrice*input.quantity,payout:input.quantity,pnl:0,status:'OPEN',txHash:String(receipt?.transactionHash??''),timestamp:Date.now()};}
  async calibration():Promise<CalibrationMetrics>{if(this.calibrationCache&&Date.now()-this.calibrationCache.at<60000)return this.calibrationCache.value;let past:any[]=[];for(const asset of ['BTC','ETH'] as const){const rows=await this.exchange.client.listPastBinaryMarkets({status:'Finalized',asset,limit:40});past.push(...rows);}const predictions:{p:number;y:number}[]=[];for(const m of past.slice(0,80)){try{const resolution=await this.exchange.client.getMarketResolution(m.marketId);const open=Number(resolution?.openingAnswer?.numericValue??0);const close=Number(resolution?.closingAnswer?.numericValue??0);if(!(open>0&&close>0))continue;const pool=m.poolAddress??m.pool;const from=millis(m.tradingStart??m.startTime??0);const to=Math.max(from, millis(m.expiry??0)-60000);if(!pool||!from||!to||to<=from)continue;const candles=await this.exchange.client.getCandles(pool,60,{from,to});const last=Array.isArray(candles)?candles[candles.length-1]:undefined;const current=Number(last?.close??last?.c??last?.closePrice??0);if(!(current>0))continue;const asset=(String(m.asset).toUpperCase().startsWith('ETH')?'ETH':'BTC') as 'BTC'|'ETH';const tau=Math.max((millis(m.expiry)-Date.now())/1000,60);const horizon=Math.max((millis(m.expiry)-millis(last?.timestamp??last?.time??m.expiry))/1000,60);const p=fairProbability(current,open,volatilityFor(asset),horizon);predictions.push({p,y:close>=open?1:0});}catch{continue;}}const bins=[0,0,0,0,0].map((_,i)=>({label:`${i*20}–${i*20+20}%`,count:0,predicted:0,observed:0}));let brier=0,psum=0,ysum=0;for(const x of predictions){brier+=(x.p-x.y)**2;psum+=x.p;ysum+=x.y;const idx=Math.min(4,Math.floor(x.p*5));bins[idx].count++;bins[idx].predicted+=x.p;bins[idx].observed+=x.y;}const normalized:CalibrationBin[]=bins.filter(b=>b.count>0).map(b=>({...b,predicted:b.predicted/b.count,observed:b.observed/b.count}));const meanPredicted=predictions.length?psum/predictions.length:null;const observedRate=predictions.length?ysum/predictions.length:null;const calibrationError=meanPredicted!==null&&observedRate!==null?Math.abs(meanPredicted-observedRate):null;const value:CalibrationMetrics={available:predictions.length>=10,source:`${this.network==='shannon'?'Somnia Shannon':'Somnia Mainnet'} finalized BTC/ETH Event Contracts`,sampleSize:predictions.length,brierScore:predictions.length?brier/predictions.length:null,meanPredicted,observedRate,calibrationError,bins:normalized,asOf:Date.now()};this.calibrationCache={at:Date.now(),value};return value;}
  mode(){return 'LIVE' as const;} walletLabel(){return this.privateKey?'Server execution wallet':'Read-only live data';}
}
